
DROP TABLE CATEGORY IF EXISTS;

CREATE TABLE CATEGORY (CATEGORY_NO INTEGER NOT NULL, CATEGORY_NAME VARCHAR(255), PARENT_NO INTEGER, DEPTH INTEGER NOT NULL, PRIMARY KEY (CATEGORY_NO));

DROP TABLE PRODUCT IF EXISTS;

CREATE TABLE PRODUCT (PRODUCT_NO BIGINT NOT NULL, BRAND_NAME VARCHAR(255), PRODUCT_NAME VARCHAR(255), PRODUCT_PRICE DECIMAL(19,2), CATEGORY_NO INTEGER, PRIMARY KEY (PRODUCT_NO));
